require_relative "../chess.rb"
module Chess
  BLACK_KNIGHT_REPRESENTATION = "\u265e"
  WHITE_KNIGHT_REPRESENTATION = "\u2658"

  WHITE_KING_REPRESENTATION = "\u2654"
  BLACK_KING_REPRESENTATION = "\u265A"

  WHITE_QUEEN_REPRESENTATION = "\u2655"
  BLACK_QUEEN_REPRESENTATION = "\u265B"

  WHITE_ROOK_REPRESENTAITON = "\u2656"
  BLACK_ROOK_REPRESENTAITON = "\u265C"

  BLACK_BISHOP_REPRESENTATION = "\u265D"
  WHITE_BISHOP_REPRESENTATION = "\u2657"

  BLACK_PAWN_REPRESENTATION = "\u265F"
  WHITE_PAWN_REPRESENTATION = "\u2659"
end

def print_all
  include Chess
  puts BLACK_BISHOP_REPRESENTATION
  puts BLACK_ROOK_REPRESENTAITON
  puts BLACK_QUEEN_REPRESENTATION
  puts BLACK_KING_REPRESENTATION
  puts BLACK_KNIGHT_REPRESENTATION
  puts BLACK_PAWN_REPRESENTATION
end


