# board_characters.
require_relative "../game.rb"
require_relative "./pieces.rb"
require_relative "./board.rb"
require_relative "./board_characters.rb"  
require_relative "./game_engine.rb"  
module Chess
  BLACK_KNIGHT_REPRESENTATION = "\u2658"
  WHITE_KNIGHT_REPRESENTATION = "\u265E"

  WHITE_KING_REPRESENTATION = "\u265A"
  BLACK_KING_REPRESENTATION = "\u2654"

  WHITE_QUEEN_REPRESENTATION = "\u265B"
  BLACK_QUEEN_REPRESENTATION = "\u2655"

  WHITE_ROOK_REPRESENTATION = "\u265C"
  BLACK_ROOK_REPRESENTATION = "\u2656"

  BLACK_BISHOP_REPRESENTATION = "\u2657"
  WHITE_BISHOP_REPRESENTATION = "\u265D"

  BLACK_PAWN_REPRESENTATION = "\u2659"
  WHITE_PAWN_REPRESENTATION = "\u265F"

  REP_MAP = {nil => "", :pawn => {:black => BLACK_PAWN_REPRESENTATION, :white => WHITE_PAWN_REPRESENTATION},
     :king => {:white => WHITE_KING_REPRESENTATION, :black => BLACK_KING_REPRESENTATION},
     :queen => {:black => BLACK_QUEEN_REPRESENTATION, :white => WHITE_QUEEN_REPRESENTATION},
     :rook => {:white => WHITE_ROOK_REPRESENTATION, :black => BLACK_ROOK_REPRESENTATION}, 
     :bishop => {:black => BLACK_BISHOP_REPRESENTATION, :white => WHITE_BISHOP_REPRESENTATION}, 
     :knight => {:black => BLACK_KNIGHT_REPRESENTATION, :white => WHITE_KNIGHT_REPRESENTATION}
    }
end

def print_all
  include Chess
  puts BLACK_BISHOP_REPRESENTATION
  puts BLACK_ROOK_REPRESENTATION
  puts BLACK_QUEEN_REPRESENTATION
  puts BLACK_KING_REPRESENTATION
  puts BLACK_KNIGHT_REPRESENTATION
  puts BLACK_PAWN_REPRESENTATION
end


