require_relative "../chess.rb"
module Chess
  BLACK_KNIGHT_REPRESENTATION = "\u265e"
  WHITE_KNIGHT_REPRESENTATION = "\u2658"

  WHITE_KING_REPRESENTATION = "\u2654"
  BLACK_KING_REPRESENTATION = "\u265A"

  WHITE_QUEEN_REPRESENTATION = "\u2655"
  BLACK_QUEEN_REPRESENTATION = "\u265B"

  WHITE_ROOK_REPRESENTATION = "\u2656"
  BLACK_ROOK_REPRESENTATION = "\u265C"

  BLACK_BISHOP_REPRESENTATION = "\u265D"
  WHITE_BISHOP_REPRESENTATION = "\u2657"

  BLACK_PAWN_REPRESENTATION = "\u265F"
  WHITE_PAWN_REPRESENTATION = "\u2659"

  rep_map = {:pawn => {:black => BLACK_PAWN_REPRESENTATION, :white => WHITE_PAWN_REPRESENTATION}, :king => {:white => WHITE_KNIGHT_REPRESENTATION, :black => BLACK_KING_REPRESENTATION},
   :queen => {:black => BLACK_QUEEN_REPRESENTATION, :white => WHITE_QUEEN_REPRESENTATION}, :rook => {:white => WHITE_ROOK_REPRESENTATION, :black => BLACK_ROOK_REPRESENTATION}, :bishop => {:black => BLACK_BISHOP_REPRESENTATION, :white => WHITE_BISHOP_REPRESENTATION}}
end

def print_all
  include Chess
  puts BLACK_BISHOP_REPRESENTATION
  puts BLACK_ROOK_REPRESENTATION
  puts BLACK_QUEEN_REPRESENTATION
  puts BLACK_KING_REPRESENTATION
  puts BLACK_KNIGHT_REPRESENTATION
  puts BLACK_PAWN_REPRESENTATION
end


